# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - simpleApp221

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerregistery2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e4e5c54c8836498aac31ed57814c5dd6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4480f95824b6441dab1ab520b4f833af }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerregistery2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e4e5c54c8836498aac31ed57814c5dd6 }}/imagedocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'simpleApp221'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd4e78e1398b44a5b29ea61187f260ab }}
        images: 'containerregistery2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e4e5c54c8836498aac31ed57814c5dd6 }}/imagedocker:${{ github.sha }}'